#[derive(Clone)]
pub struct Attr {
   pub name: String,
   pub value: String,
}

impl Attr {
   pub fn new<N: Into<String>>(name: N, value: String) -> Self {
      Attr {
         name: name.into(),
         value: value
      }
   }
   
   pub fn value(&mut self, value: String) {
      self.value = value;
   }
}

impl std::fmt::Display for Attr {
   fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
      write!(
         f, 
         "{}='{}'",
         self.name,
         self.value
      )
   }
}

#[derive(Clone)]
pub enum AttrName {
   Accept,
   AcceptCharset,
   AccessKey,
   Action,
   Align,
   Alt,
   Async,
   AutoComplete,
   AutoFocus,
   AutoPlay,
   BackgroundColor,
   Border,
   Charset,
   Checked,
   Cite,
   Class,
   Color,
   Columns,
   ColumnSpan,
   Content,
   ContentEditable,
   Controls,
   Coords,
   Data,
   DateTime,
   Default_,
   Defer,
   Dir,
   DirName,
   Disabled,
   Download,
   Draggable,
   DropZone,
   EncodingType,
   For,
   Form,
   FormAction,
   Headers,
   Height,
   Hidden,
   High,
   Href,
   Hreflang,
   HttpEquivalent,
   Id,
   Identifier,
   IsMap,
   Kind,
   Label,
   Language,
   List,
   Loop,
   Low,
   Max,
   MaxLength,
   Media,
   Method,
   Min,
   Multiple,
   Muted,
   Name,
   NoValidate,
   OnAbort,
   OnAfterPrint,
   OnBeforePrint,
   OnBeforeUnload,
   OnBlur,
   OnCanPlay,
   OnCanPlayThrough,
   OnChange,
   OnClick,
   OnContextMenu,
   OnCopy,
   OnCueChange,
   OnCut,
   OnDoubleClick,
   OnDrag,
   OnDragEnd,
   OnDragEnter,
   OnDragLeave,
   OnDragOver,
   OnDragStart,
   OnDrop,
   OnDurationChange,
   OnEmptied,
   OnEnded,
   OnError,
   OnFocus,
   OnHashChange,
   OnInput,
   OnInvalid,
   OnKeyDown,
   OnKeyPress,
   OnKeyUp,
   OnLoad,
   OnLoadedData,
   OnLoadedMetadata,
   OnLoadStart,
   OnMouseDown,
   OnMouseMove,
   OnMouseOut,
   OnMouseOver,
   OnMouseUp,
   OnMouseWheel,
   OnOffline,
   OnOnline,
   OnPageHide,
   OnPageShow,
   OnPaste,
   OnPause,
   OnPlay,
   OnPlaying,
   OnPopState,
   OnProgress,
   OnRateChange,
   OnReset,
   OnResize,
   OnScroll,
   OnSearch,
   OnSeeked,
   OnSeeking,
   OnSelect,
   OnStalled,
   OnStorage,
   OnSubmit,
   OnSuspend,
   OnTimeUpdate,
   OnToggle,
   OnUnload,
   OnVolumeChange,
   OnWaiting,
   OnWheel,
   Open,
   Optimum,
   Pattern,
   Placeholder,
   Poster,
   Preload,
   ReadOnly,
   Relative,
   Required,
   Reversed,
   Rows,
   RowSpan,
   Sandbox,
   Scope,
   Selected,
   Shape,
   Size,
   Sizes,
   Span,
   Spellcheck,
   Source,
   SourceDoc,
   SourceLanguage,
   SourceSet,
   Start,
   Step,
   // Style,
   TabIndex,
   Target,
   Title,
   Translate,
   Type,
   UseMap,
   Value,
   Width,
   Wrap,
}

impl std::convert::Into<String> for AttrName {
   fn into(self) -> String {
      match self {
         AttrName::Accept => "accept",
         AttrName::AcceptCharset => "accept-charset",
         AttrName::AccessKey => "accesskey",
         AttrName::Action => "action",
         AttrName::Align => "align",
         AttrName::Alt => "alt",
         AttrName::Async => "async",
         AttrName::AutoComplete => "autocomplete",
         AttrName::AutoFocus => "autofocus",
         AttrName::AutoPlay => "autoplay",
         AttrName::BackgroundColor => "bgcolor",
         AttrName::Border => "border",
         AttrName::Charset => "charset",
         AttrName::Checked => "checked",
         AttrName::Cite => "cite",
         AttrName::Class => "class",
         AttrName::Color => "color",
         AttrName::Columns => "cols",
         AttrName::ColumnSpan => "colspan",
         AttrName::Content => "content",
         AttrName::ContentEditable => "contenteditable",
         AttrName::Controls => "controls",
         AttrName::Coords => "coords",
         AttrName::Data => "data",
         AttrName::DateTime => "datetime",
         AttrName::Default_ => "default",
         AttrName::Defer => "defer",
         AttrName::Dir => "dir",
         AttrName::DirName => "dirname",
         AttrName::Disabled => "disabled",
         AttrName::Download => "download",
         AttrName::Draggable => "draggable",
         AttrName::DropZone => "dropzone",
         AttrName::EncodingType => "enctype",
         AttrName::For => "for",
         AttrName::Form => "form",
         AttrName::FormAction => "formaction",
         AttrName::Headers => "headers",
         AttrName::Height => "height",
         AttrName::Hidden => "hidden",
         AttrName::High => "high",
         AttrName::Href => "href",
         AttrName::Hreflang => "hreflang",
         AttrName::HttpEquivalent => "http-equiv",
         AttrName::Id => "id",
         AttrName::Identifier => "id",
         AttrName::IsMap => "ismap",
         AttrName::Kind => "kind",
         AttrName::Label => "label",
         AttrName::Language => "lang",
         AttrName::List => "list",
         AttrName::Loop => "loop",
         AttrName::Low => "low",
         AttrName::Max => "max",
         AttrName::MaxLength => "maxlength",
         AttrName::Media => "media",
         AttrName::Method => "method",
         AttrName::Min => "min",
         AttrName::Multiple => "multiple",
         AttrName::Muted => "muted",
         AttrName::Name => "name",
         AttrName::NoValidate => "novalidate",
         AttrName::OnAbort => "onabort",
         AttrName::OnAfterPrint => "onafterprint",
         AttrName::OnBeforePrint => "onbeforeprint",
         AttrName::OnBeforeUnload => "onbeforeunload",
         AttrName::OnBlur => "onblur",
         AttrName::OnCanPlay => "oncanplay",
         AttrName::OnCanPlayThrough => "oncanplaythrough",
         AttrName::OnChange => "onchange",
         AttrName::OnClick => "onclick",
         AttrName::OnContextMenu => "oncontextmenu",
         AttrName::OnCopy => "oncopy",
         AttrName::OnCueChange => "oncuechange",
         AttrName::OnCut => "oncut",
         AttrName::OnDoubleClick => "ondblclick",
         AttrName::OnDrag => "ondrag",
         AttrName::OnDragEnd => "ondragend",
         AttrName::OnDragEnter => "ondragenter",
         AttrName::OnDragLeave => "ondragleave",
         AttrName::OnDragOver => "ondragover",
         AttrName::OnDragStart => "ondragstart",
         AttrName::OnDrop => "ondrop",
         AttrName::OnDurationChange => "ondurationchange",
         AttrName::OnEmptied => "onemptied",
         AttrName::OnEnded => "onended",
         AttrName::OnError => "onerror",
         AttrName::OnFocus => "onfocus",
         AttrName::OnHashChange => "onhashchange",
         AttrName::OnInput => "oninput",
         AttrName::OnInvalid => "oninvalid",
         AttrName::OnKeyDown => "onkeydown",
         AttrName::OnKeyPress => "onkeypress",
         AttrName::OnKeyUp => "onkeyup",
         AttrName::OnLoad => "onload",
         AttrName::OnLoadedData => "onloadeddata",
         AttrName::OnLoadedMetadata => "onloadedmetadata",
         AttrName::OnLoadStart => "onloadstart",
         AttrName::OnMouseDown => "onmousedown",
         AttrName::OnMouseMove => "onmousemove",
         AttrName::OnMouseOut => "onmouseout",
         AttrName::OnMouseOver => "onmouseover",
         AttrName::OnMouseUp => "onmouseup",
         AttrName::OnMouseWheel => "onmousewheel",
         AttrName::OnOffline => "onoffline",
         AttrName::OnOnline => "ononline",
         AttrName::OnPageHide => "onpagehide",
         AttrName::OnPageShow => "onpageshow",
         AttrName::OnPaste => "onpaste",
         AttrName::OnPause => "onpause",
         AttrName::OnPlay => "onplay",
         AttrName::OnPlaying => "onplaying",
         AttrName::OnPopState => "onpopstate",
         AttrName::OnProgress => "onprogress",
         AttrName::OnRateChange => "onratechange",
         AttrName::OnReset => "onreset",
         AttrName::OnResize => "onresize",
         AttrName::OnScroll => "onscroll",
         AttrName::OnSearch => "onsearch",
         AttrName::OnSeeked => "onseeked",
         AttrName::OnSeeking => "onseeking",
         AttrName::OnSelect => "onselect",
         AttrName::OnStalled => "onstalled",
         AttrName::OnStorage => "onstorage",
         AttrName::OnSubmit => "onsubmit",
         AttrName::OnSuspend => "onsuspend",
         AttrName::OnTimeUpdate => "ontimeupdate",
         AttrName::OnToggle => "ontoggle",
         AttrName::OnUnload => "onunload",
         AttrName::OnVolumeChange => "onvolumechange",
         AttrName::OnWaiting => "onwaiting",
         AttrName::OnWheel => "onwheel",
         AttrName::Open => "open",
         AttrName::Optimum => "optimum",
         AttrName::Pattern => "pattern",
         AttrName::Placeholder => "placeholder",
         AttrName::Poster => "poster",
         AttrName::Preload => "preload",
         AttrName::ReadOnly => "readonly",
         AttrName::Relative => "rel",
         AttrName::Required => "required",
         AttrName::Reversed => "reversed",
         AttrName::Rows => "rows",
         AttrName::RowSpan => "rowspan",
         AttrName::Sandbox => "sandbox",
         AttrName::Scope => "scope",
         AttrName::Selected => "selected",
         AttrName::Shape => "shape",
         AttrName::Size => "size",
         AttrName::Sizes => "sizes",
         AttrName::Span => "span",
         AttrName::Spellcheck => "spellcheck",
         AttrName::Source => "src",
         AttrName::SourceDoc => "srcdoc",
         AttrName::SourceLanguage => "srclang",
         AttrName::SourceSet => "srcset",
         AttrName::Start => "start",
         AttrName::Step => "step",
         // AttrName::Style => "style",
         AttrName::TabIndex => "tabindex",
         AttrName::Target => "target",
         AttrName::Title => "title",
         AttrName::Translate => "translate",
         AttrName::Type => "type",
         AttrName::UseMap => "usemap",
         AttrName::Value => "value",
         AttrName::Width => "width",
         AttrName::Wrap => "wrap",
      }.into()
   }
}