/// List of CSS properties.
#[derive(Clone)]
pub enum Prop {
   AlignContent,
   AlignItems,
   AlignSelf,
   All,
   Animation,
   AnimationDelay,
   AnimationDirection,
   AnimationDuration,
   AnimationFillMode,
   AnimationIterationCount,
   AnimationName,
   AnimationPlayState,
   AnimationTimingFunction,
   BackfaceVisibility,
   Background,
   BackgroundAttachment,
   BackgroundBlendMode,
   BackgroundClip,
   BackgroundColor,
   BackgroundImage,
   BackgroundOrigin,
   BackgroundPosition,
   BackgroundRepeat,
   BackgroundSize,
   Border,
   BorderBottom,
   BorderBottomColor,
   BorderBottomLeftRadius,
   BorderBottomRightRadius,
   BorderBottomStyle,
   BorderBottomWidth,
   BorderCollapse,
   BorderColor,
   BorderImage,
   BorderImageOutset,
   BorderImageRepeat,
   BorderImageSlice,
   BorderImageSource,
   BorderImageWidth,
   BorderLeft,
   BorderLeftColor,
   BorderLeftStyle,
   BorderLeftWidth,
   BorderRadius,
   BorderRight,
   BorderRightColor,
   BorderRightStyle,
   BorderRightWidth,
   BorderSpacing,
   BorderStyle,
   BorderTop,
   BorderTopColor,
   BorderTopLeftRadius,
   BorderTopRightRadius,
   BorderTopStyle,
   BorderTopWidth,
   BorderWidth,
   Bottom,
   BoxDecorationBreak,
   BoxShadow,
   BoxSizing,
   BreakAfter,
   BreakBefore,
   BreakInside,
   CaptionSide,
   CaretColor,
   Clear,
   Clip,
   Color,
   ColumnCount,
   ColumnFill,
   ColumnGap,
   ColumnRule,
   ColumnRuleColor,
   ColumnRuleStyle,
   ColumnRuleWidth,
   ColumnSpan,
   ColumnWidth,
   Columns,
   Content,
   CounterIncrement,
   CounterReset,
   Cursor,
   Direction,
   Display,
   EmptyCells,
   Filter,
   Flex,
   FlexBasis,
   FlexDirection,
   FlexFlow,
   FlexGrow,
   FlexShrink,
   FlexWrap,
   Float,
   Font,
   FontFamily,
   FontFeatureSettings,
   FontKerning,
   FontLanguageOverride,
   FontSize,
   FontSizeAdjust,
   FontStretch,
   FontStyle,
   FontSynthesis,
   FontVariant,
   FontVariantAlternates,
   FontVariantCaps,
   FontVariantEastAsian,
   FontVariantLigatures,
   FontVariantNumeric,
   FontVariantPosition,
   FontWeight,
   Grid,
   GridArea,
   GridAutoColumns,
   GridAutoFlow,
   GridAutoRows,
   GridColumn,
   GridColumnEnd,
   GridColumnGap,
   GridColumnStart,
   GridGap,
   GridRow,
   GridRowEnd,
   GridRowGap,
   GridRowStart,
   GridTemplate,
   GridTemplateAreas,
   GridTemplateColumns,
   GridTemplateRows,
   HangingPunctuation,
   Height,
   Hyphens,
   ImageRendering,
   Isolation,
   JustifyContent,
   Left,
   LetterSpacing,
   LineBreak,
   LineHeight,
   ListStyle,
   ListStyleImage,
   ListStylePosition,
   ListStyleType,
   Margin,
   MarginBottom,
   MarginLeft,
   MarginRight,
   MarginTop,
   MaxHeight,
   MaxWidth,
   MinHeight,
   MinWidth,
   MixBlendMode,
   ObjectFit,
   ObjectPosition,
   Opacity,
   Order,
   Orphans,
   Outline,
   OutlineColor,
   OutlineOffset,
   OutlineStyle,
   OutlineWidth,
   Overflow,
   OverflowWrap,
   OverflowX,
   OverflowY,
   Padding,
   PaddingBottom,
   PaddingLeft,
   PaddingRight,
   PaddingTop,
   PageBreakAfter,
   PageBreakBefore,
   PageBreakInside,
   Perspective,
   PerspectiveOrigin,
   PointerEvents,
   Position,
   Quotes,
   Resize,
   Right,
   ScrollBehavior,
   TabSize,
   TableLayout,
   TextAlign,
   TextAlignLast,
   TextCombineUpright,
   TextDecoration,
   TextDecorationColor,
   TextDecorationLine,
   TextDecorationStyle,
   TextIndent,
   TextJustify,
   TextOrientation,
   TextOverflow,
   TextShadow,
   TextTransform,
   TextUnderlinePosition,
   Top,
   Transform,
   TransformOrigin,
   TransformStyle,
   Transition,
   TransitionDelay,
   TransitionDuration,
   TransitionProperty,
   TransitionTimingFunction,
   UnicodeBidi,
   UserSelect,
   VerticalAlign,
   Visibility,
   WhiteSpace,
   Widows,
   Width,
   WordBreak,
   WordSpacing,
   WordWrap,
   WritingMode,
   ZIndex,
}

impl std::convert::From<Prop> for String {
   fn from(prop: Prop) -> Self {
      match prop {
         Prop::AlignContent => "align-content",
         Prop::AlignItems => "align-items",
         Prop::AlignSelf => "align-self",
         Prop::All => "all",
         Prop::Animation => "animation",
         Prop::AnimationDelay => "animation-delay",
         Prop::AnimationDirection => "animation-direction",
         Prop::AnimationDuration => "animation-duration",
         Prop::AnimationFillMode => "animation-fill-mode",
         Prop::AnimationIterationCount => "animation-iteration-count",
         Prop::AnimationName => "animation-name",
         Prop::AnimationPlayState => "animation-play-state",
         Prop::AnimationTimingFunction => "animation-timing-function",
         Prop::BackfaceVisibility => "backface-visibility",
         Prop::Background => "background",
         Prop::BackgroundAttachment => "background-attachment",
         Prop::BackgroundBlendMode => "background-blend-mode",
         Prop::BackgroundClip => "background-clip",
         Prop::BackgroundColor => "background-color",
         Prop::BackgroundImage => "background-image",
         Prop::BackgroundOrigin => "background-origin",
         Prop::BackgroundPosition => "background-position",
         Prop::BackgroundRepeat => "background-repeat",
         Prop::BackgroundSize => "background-size",
         Prop::Border => "border",
         Prop::BorderBottom => "border-bottom",
         Prop::BorderBottomColor => "border-bottom-color",
         Prop::BorderBottomLeftRadius => "border-bottom-left-radius",
         Prop::BorderBottomRightRadius => "border-bottom-right-radius",
         Prop::BorderBottomStyle => "border-bottom-style",
         Prop::BorderBottomWidth => "border-bottom-width",
         Prop::BorderCollapse => "border-collapse",
         Prop::BorderColor => "border-color",
         Prop::BorderImage => "border-image",
         Prop::BorderImageOutset => "border-image-outset",
         Prop::BorderImageRepeat => "border-image-repeat",
         Prop::BorderImageSlice => "border-image-slice",
         Prop::BorderImageSource => "border-image-source",
         Prop::BorderImageWidth => "border-image-width",
         Prop::BorderLeft => "border-left",
         Prop::BorderLeftColor => "border-left-color",
         Prop::BorderLeftStyle => "border-left-style",
         Prop::BorderLeftWidth => "border-left-width",
         Prop::BorderRadius => "border-radius",
         Prop::BorderRight => "border-right",
         Prop::BorderRightColor => "border-right-color",
         Prop::BorderRightStyle => "border-right-style",
         Prop::BorderRightWidth => "border-right-width",
         Prop::BorderSpacing => "border-spacing",
         Prop::BorderStyle => "border-style",
         Prop::BorderTop => "border-top",
         Prop::BorderTopColor => "border-top-color",
         Prop::BorderTopLeftRadius => "border-top-left-radius",
         Prop::BorderTopRightRadius => "border-top-right-radius",
         Prop::BorderTopStyle => "border-top-style",
         Prop::BorderTopWidth => "border-top-width",
         Prop::BorderWidth => "border-width",
         Prop::Bottom => "bottom",
         Prop::BoxDecorationBreak => "box-decoration-break",
         Prop::BoxShadow => "box-shadow",
         Prop::BoxSizing => "box-sizing",
         Prop::BreakAfter => "break-after",
         Prop::BreakBefore => "break-before",
         Prop::BreakInside => "break-inside",
         Prop::CaptionSide => "caption-side",
         Prop::CaretColor => "caret-color",
         Prop::Clear => "clear",
         Prop::Clip => "clip",
         Prop::Color => "color",
         Prop::ColumnCount => "column-count",
         Prop::ColumnFill => "column-fill",
         Prop::ColumnGap => "column-gap",
         Prop::ColumnRule => "column-rule",
         Prop::ColumnRuleColor => "column-rule-color",
         Prop::ColumnRuleStyle => "column-rule-style",
         Prop::ColumnRuleWidth => "column-rule-width",
         Prop::ColumnSpan => "column-span",
         Prop::ColumnWidth => "column-width",
         Prop::Columns => "columns",
         Prop::Content => "content",
         Prop::CounterIncrement => "counter-increment",
         Prop::CounterReset => "counter-reset",
         Prop::Cursor => "cursor",
         Prop::Direction => "direction",
         Prop::Display => "display",
         Prop::EmptyCells => "empty-cells",
         Prop::Filter => "filter",
         Prop::Flex => "flex",
         Prop::FlexBasis => "flex-basis",
         Prop::FlexDirection => "flex-direction",
         Prop::FlexFlow => "flex-flow",
         Prop::FlexGrow => "flex-grow",
         Prop::FlexShrink => "flex-shrink",
         Prop::FlexWrap => "flex-wrap",
         Prop::Float => "float",
         Prop::Font => "font",
         Prop::FontFamily => "font-family",
         Prop::FontFeatureSettings => "font-feature-settings",
         Prop::FontKerning => "font-kerning",
         Prop::FontLanguageOverride => "font-language-override",
         Prop::FontSize => "font-size",
         Prop::FontSizeAdjust => "font-size-adjust",
         Prop::FontStretch => "font-stretch",
         Prop::FontStyle => "font-style",
         Prop::FontSynthesis => "font-synthesis",
         Prop::FontVariant => "font-variant",
         Prop::FontVariantAlternates => "font-variant-alternates",
         Prop::FontVariantCaps => "font-variant-caps",
         Prop::FontVariantEastAsian => "font-variant-east-asian",
         Prop::FontVariantLigatures => "font-variant-ligatures",
         Prop::FontVariantNumeric => "font-variant-numeric",
         Prop::FontVariantPosition => "font-variant-position",
         Prop::FontWeight => "font-weight",
         Prop::Grid => "grid",
         Prop::GridArea => "grid-area",
         Prop::GridAutoColumns => "grid-auto-columns",
         Prop::GridAutoFlow => "grid-auto-flow",
         Prop::GridAutoRows => "grid-auto-rows",
         Prop::GridColumn => "grid-column",
         Prop::GridColumnEnd => "grid-column-end",
         Prop::GridColumnGap => "grid-column-gap",
         Prop::GridColumnStart => "grid-column-start",
         Prop::GridGap => "grid-gap",
         Prop::GridRow => "grid-row",
         Prop::GridRowEnd => "grid-row-end",
         Prop::GridRowGap => "grid-row-gap",
         Prop::GridRowStart => "grid-row-start",
         Prop::GridTemplate => "grid-template",
         Prop::GridTemplateAreas => "grid-template-areas",
         Prop::GridTemplateColumns => "grid-template-columns",
         Prop::GridTemplateRows => "grid-template-rows",
         Prop::HangingPunctuation => "hanging-punctuation",
         Prop::Height => "height",
         Prop::Hyphens => "hyphens",
         Prop::ImageRendering => "image-rendering",
         Prop::Isolation => "isolation",
         Prop::JustifyContent => "justify-content",
         Prop::Left => "left",
         Prop::LetterSpacing => "letter-spacing",
         Prop::LineBreak => "line-break",
         Prop::LineHeight => "line-height",
         Prop::ListStyle => "list-style",
         Prop::ListStyleImage => "list-style-image",
         Prop::ListStylePosition => "list-style-position",
         Prop::ListStyleType => "list-style-type",
         Prop::Margin => "margin",
         Prop::MarginBottom => "margin-bottom",
         Prop::MarginLeft => "margin-left",
         Prop::MarginRight => "margin-right",
         Prop::MarginTop => "margin-top",
         Prop::MaxHeight => "max-height",
         Prop::MaxWidth => "max-width",
         Prop::MinHeight => "min-height",
         Prop::MinWidth => "min-width",
         Prop::MixBlendMode => "mix-blend-mode",
         Prop::ObjectFit => "object-fit",
         Prop::ObjectPosition => "object-position",
         Prop::Opacity => "opacity",
         Prop::Order => "order",
         Prop::Orphans => "orphans",
         Prop::Outline => "outline",
         Prop::OutlineColor => "outline-color",
         Prop::OutlineOffset => "outline-offset",
         Prop::OutlineStyle => "outline-style",
         Prop::OutlineWidth => "outline-width",
         Prop::Overflow => "overflow",
         Prop::OverflowWrap => "overflow-wrap",
         Prop::OverflowX => "overflow-x",
         Prop::OverflowY => "overflow-y",
         Prop::Padding => "padding",
         Prop::PaddingBottom => "padding-bottom",
         Prop::PaddingLeft => "padding-left",
         Prop::PaddingRight => "padding-right",
         Prop::PaddingTop => "padding-top",
         Prop::PageBreakAfter => "page-break-after",
         Prop::PageBreakBefore => "page-break-before",
         Prop::PageBreakInside => "page-break-inside",
         Prop::Perspective => "perspective",
         Prop::PerspectiveOrigin => "perspective-origin",
         Prop::PointerEvents => "pointer-events",
         Prop::Position => "position",
         Prop::Quotes => "quotes",
         Prop::Resize => "resize",
         Prop::Right => "right",
         Prop::ScrollBehavior => "scroll-behavior",
         Prop::TabSize => "tab-size",
         Prop::TableLayout => "table-layout",
         Prop::TextAlign => "text-align",
         Prop::TextAlignLast => "text-align-last",
         Prop::TextCombineUpright => "text-combine-upright",
         Prop::TextDecoration => "text-decoration",
         Prop::TextDecorationColor => "text-decoration-color",
         Prop::TextDecorationLine => "text-decoration-line",
         Prop::TextDecorationStyle => "text-decoration-style",
         Prop::TextIndent => "text-indent",
         Prop::TextJustify => "text-justify",
         Prop::TextOrientation => "text-orientation",
         Prop::TextOverflow => "text-overflow",
         Prop::TextShadow => "text-shadow",
         Prop::TextTransform => "text-transform",
         Prop::TextUnderlinePosition => "text-underline-position",
         Prop::Top => "top",
         Prop::Transform => "transform",
         Prop::TransformOrigin => "transform-origin",
         Prop::TransformStyle => "transform-style",
         Prop::Transition => "transition",
         Prop::TransitionDelay => "transition-delay",
         Prop::TransitionDuration => "transition-duration",
         Prop::TransitionProperty => "transition-property",
         Prop::TransitionTimingFunction => "transition-timing-function",
         Prop::UnicodeBidi => "unicode-bidi",
         Prop::UserSelect => "user-select",
         Prop::VerticalAlign => "vertical-align",
         Prop::Visibility => "visibility",
         Prop::WhiteSpace => "white-space",
         Prop::Widows => "widows",
         Prop::Width => "width",
         Prop::WordBreak => "word-break",
         Prop::WordSpacing => "word-spacing",
         Prop::WordWrap => "word-wrap",
         Prop::WritingMode => "writing-mode",
         Prop::ZIndex => "z-index",
      }.into()
   }
}