#[derive(Clone)]
pub struct Attr {
   name: String,
   value: String,
}

impl Attr {
   pub fn new<N: Into<String>>(name: N, value: String) -> Self {
      Attr {
         name: name.into(),
         value: value
      }
   }
   
   pub fn value(&mut self, value: String) {
      self.value = value;
   }
}

impl std::fmt::Display for Attr {
   fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
      write!(
         f, 
         "{}='{}'",
         self.name,
         self.value
      )
   }
}

#[derive(Clone)]
pub enum AttrName {
   accept,
   accept_charset,
   accesskey,
   action,
   align,
   alt,
   _async,
   autocomplete,
   autofocus,
   autoplay,
   bgcolor,
   border,
   charset,
   checked,
   cite,
   class,
   color,
   cols,
   colspan,
   content,
   contenteditable,
   controls,
   coords,
   data,
   data_STAR,
   datetime,
   default,
   defer,
   dir,
   dirname,
   disabled,
   download,
   draggable,
   dropzone,
   enctype,
   _for,
   form,
   formaction,
   headers,
   height,
   hidden,
   high,
   href,
   hreflang,
   http_equiv,
   id,
   ismap,
   kind,
   label,
   lang,
   list,
   _loop,
   low,
   max,
   maxlength,
   media,
   method,
   min,
   multiple,
   muted,
   name,
   novalidate,
   onabort,
   onafterprint,
   onbeforeprint,
   onbeforeunload,
   onblur,
   oncanplay,
   oncanplaythrough,
   onchange,
   onclick,
   oncontextmenu,
   oncopy,
   oncuechange,
   oncut,
   ondblclick,
   ondrag,
   ondragend,
   ondragenter,
   ondragleave,
   ondragover,
   ondragstart,
   ondrop,
   ondurationchange,
   onemptied,
   onended,
   onerror,
   onfocus,
   onhashchange,
   oninput,
   oninvalid,
   onkeydown,
   onkeypress,
   onkeyup,
   onload,
   onloadeddata,
   onloadedmetadata,
   onloadstart,
   onmousedown,
   onmousemove,
   onmouseout,
   onmouseover,
   onmouseup,
   onmousewheel,
   onoffline,
   ononline,
   onpagehide,
   onpageshow,
   onpaste,
   onpause,
   onplay,
   onplaying,
   onpopstate,
   onprogress,
   onratechange,
   onreset,
   onresize,
   onscroll,
   onsearch,
   onseeked,
   onseeking,
   onselect,
   onstalled,
   onstorage,
   onsubmit,
   onsuspend,
   ontimeupdate,
   ontoggle,
   onunload,
   onvolumechange,
   onwaiting,
   onwheel,
   open,
   optimum,
   pattern,
   placeholder,
   poster,
   preload,
   readonly,
   rel,
   required,
   reversed,
   rows,
   rowspan,
   sandbox,
   scope,
   selected,
   shape,
   size,
   sizes,
   span,
   spellcheck,
   src,
   srcdoc,
   srclang,
   srcset,
   start,
   step,
   style,
   tabindex,
   target,
   title,
   translate,
   _type,
   usemap,
   value,
   width,
   wrap,
}

impl std::convert::Into<String> for AttrName {
   fn into(self) -> String {
      match self {
         AttrName::accept => "accept",
         AttrName::accept_charset => "accept-charset",
         AttrName::accesskey => "accesskey",
         AttrName::action => "action",
         AttrName::align => "align",
         AttrName::alt => "alt",
         AttrName::_async => "async",
         AttrName::autocomplete => "autocomplete",
         AttrName::autofocus => "autofocus",
         AttrName::autoplay => "autoplay",
         AttrName::bgcolor => "bgcolor",
         AttrName::border => "border",
         AttrName::charset => "charset",
         AttrName::checked => "checked",
         AttrName::cite => "cite",
         AttrName::class => "class",
         AttrName::color => "color",
         AttrName::cols => "cols",
         AttrName::colspan => "colspan",
         AttrName::content => "content",
         AttrName::contenteditable => "contenteditable",
         AttrName::controls => "controls",
         AttrName::coords => "coords",
         AttrName::data => "data",
         AttrName::data_STAR => "data-*",
         AttrName::datetime => "datetime",
         AttrName::default => "default",
         AttrName::defer => "defer",
         AttrName::dir => "dir",
         AttrName::dirname => "dirname",
         AttrName::disabled => "disabled",
         AttrName::download => "download",
         AttrName::draggable => "draggable",
         AttrName::dropzone => "dropzone",
         AttrName::enctype => "enctype",
         AttrName::_for => "for",
         AttrName::form => "form",
         AttrName::formaction => "formaction",
         AttrName::headers => "headers",
         AttrName::height => "height",
         AttrName::hidden => "hidden",
         AttrName::high => "high",
         AttrName::href => "href",
         AttrName::hreflang => "hreflang",
         AttrName::http_equiv => "http-equiv",
         AttrName::id => "id",
         AttrName::ismap => "ismap",
         AttrName::kind => "kind",
         AttrName::label => "label",
         AttrName::lang => "lang",
         AttrName::list => "list",
         AttrName::_loop => "loop",
         AttrName::low => "low",
         AttrName::max => "max",
         AttrName::maxlength => "maxlength",
         AttrName::media => "media",
         AttrName::method => "method",
         AttrName::min => "min",
         AttrName::multiple => "multiple",
         AttrName::muted => "muted",
         AttrName::name => "name",
         AttrName::novalidate => "novalidate",
         AttrName::onabort => "onabort",
         AttrName::onafterprint => "onafterprint",
         AttrName::onbeforeprint => "onbeforeprint",
         AttrName::onbeforeunload => "onbeforeunload",
         AttrName::onblur => "onblur",
         AttrName::oncanplay => "oncanplay",
         AttrName::oncanplaythrough => "oncanplaythrough",
         AttrName::onchange => "onchange",
         AttrName::onclick => "onclick",
         AttrName::oncontextmenu => "oncontextmenu",
         AttrName::oncopy => "oncopy",
         AttrName::oncuechange => "oncuechange",
         AttrName::oncut => "oncut",
         AttrName::ondblclick => "ondblclick",
         AttrName::ondrag => "ondrag",
         AttrName::ondragend => "ondragend",
         AttrName::ondragenter => "ondragenter",
         AttrName::ondragleave => "ondragleave",
         AttrName::ondragover => "ondragover",
         AttrName::ondragstart => "ondragstart",
         AttrName::ondrop => "ondrop",
         AttrName::ondurationchange => "ondurationchange",
         AttrName::onemptied => "onemptied",
         AttrName::onended => "onended",
         AttrName::onerror => "onerror",
         AttrName::onfocus => "onfocus",
         AttrName::onhashchange => "onhashchange",
         AttrName::oninput => "oninput",
         AttrName::oninvalid => "oninvalid",
         AttrName::onkeydown => "onkeydown",
         AttrName::onkeypress => "onkeypress",
         AttrName::onkeyup => "onkeyup",
         AttrName::onload => "onload",
         AttrName::onloadeddata => "onloadeddata",
         AttrName::onloadedmetadata => "onloadedmetadata",
         AttrName::onloadstart => "onloadstart",
         AttrName::onmousedown => "onmousedown",
         AttrName::onmousemove => "onmousemove",
         AttrName::onmouseout => "onmouseout",
         AttrName::onmouseover => "onmouseover",
         AttrName::onmouseup => "onmouseup",
         AttrName::onmousewheel => "onmousewheel",
         AttrName::onoffline => "onoffline",
         AttrName::ononline => "ononline",
         AttrName::onpagehide => "onpagehide",
         AttrName::onpageshow => "onpageshow",
         AttrName::onpaste => "onpaste",
         AttrName::onpause => "onpause",
         AttrName::onplay => "onplay",
         AttrName::onplaying => "onplaying",
         AttrName::onpopstate => "onpopstate",
         AttrName::onprogress => "onprogress",
         AttrName::onratechange => "onratechange",
         AttrName::onreset => "onreset",
         AttrName::onresize => "onresize",
         AttrName::onscroll => "onscroll",
         AttrName::onsearch => "onsearch",
         AttrName::onseeked => "onseeked",
         AttrName::onseeking => "onseeking",
         AttrName::onselect => "onselect",
         AttrName::onstalled => "onstalled",
         AttrName::onstorage => "onstorage",
         AttrName::onsubmit => "onsubmit",
         AttrName::onsuspend => "onsuspend",
         AttrName::ontimeupdate => "ontimeupdate",
         AttrName::ontoggle => "ontoggle",
         AttrName::onunload => "onunload",
         AttrName::onvolumechange => "onvolumechange",
         AttrName::onwaiting => "onwaiting",
         AttrName::onwheel => "onwheel",
         AttrName::open => "open",
         AttrName::optimum => "optimum",
         AttrName::pattern => "pattern",
         AttrName::placeholder => "placeholder",
         AttrName::poster => "poster",
         AttrName::preload => "preload",
         AttrName::readonly => "readonly",
         AttrName::rel => "rel",
         AttrName::required => "required",
         AttrName::reversed => "reversed",
         AttrName::rows => "rows",
         AttrName::rowspan => "rowspan",
         AttrName::sandbox => "sandbox",
         AttrName::scope => "scope",
         AttrName::selected => "selected",
         AttrName::shape => "shape",
         AttrName::size => "size",
         AttrName::sizes => "sizes",
         AttrName::span => "span",
         AttrName::spellcheck => "spellcheck",
         AttrName::src => "src",
         AttrName::srcdoc => "srcdoc",
         AttrName::srclang => "srclang",
         AttrName::srcset => "srcset",
         AttrName::start => "start",
         AttrName::step => "step",
         AttrName::style => "style",
         AttrName::tabindex => "tabindex",
         AttrName::target => "target",
         AttrName::title => "title",
         AttrName::translate => "translate",
         AttrName::_type => "type",
         AttrName::usemap => "usemap",
         AttrName::value => "value",
         AttrName::width => "width",
         AttrName::wrap => "wrap",
      }.into()
   }
}