pub struct Prop {
   prop_name: PropName,
   value: String,
}

impl std::fmt::Display for Prop {
   fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
      write!(
         f, 
         "{}: {};",
         self.prop_name.to_str(),
         self.value
      )
   }
}

pub enum PropName {
   align_content,
   align_items,
   align_self,
   all,
   animation,
   animation_delay,
   animation_direction,
   animation_duration,
   animation_fill_mode,
   animation_iteration_count,
   animation_name,
   animation_play_state,
   animation_timing_function,
   backface_visibility,
   background,
   background_attachment,
   background_blend_mode,
   background_clip,
   background_color,
   background_image,
   background_origin,
   background_position,
   background_repeat,
   background_size,
   border,
   border_bottom,
   border_bottom_color,
   border_bottom_left_radius,
   border_bottom_right_radius,
   border_bottom_style,
   border_bottom_width,
   border_collapse,
   border_color,
   border_image,
   border_image_outset,
   border_image_repeat,
   border_image_slice,
   border_image_source,
   border_image_width,
   border_left,
   border_left_color,
   border_left_style,
   border_left_width,
   border_radius,
   border_right,
   border_right_color,
   border_right_style,
   border_right_width,
   border_spacing,
   border_style,
   border_top,
   border_top_color,
   border_top_left_radius,
   border_top_right_radius,
   border_top_style,
   border_top_width,
   border_width,
   bottom,
   box_decoration_break,
   box_shadow,
   box_sizing,
   break_after,
   break_before,
   break_inside,
   caption_side,
   caret_color,
   ATcharset,
   clear,
   clip,
   color,
   column_count,
   column_fill,
   column_gap,
   column_rule,
   column_rule_color,
   column_rule_style,
   column_rule_width,
   column_span,
   column_width,
   columns,
   content,
   counter_increment,
   counter_reset,
   cursor,
   direction,
   display,
   empty_cells,
   filter,
   flex,
   flex_basis,
   flex_direction,
   flex_flow,
   flex_grow,
   flex_shrink,
   flex_wrap,
   float,
   font,
   ATfont_face,
   font_family,
   font_feature_settings,
   ATfont_feature_values,
   font_kerning,
   font_language_override,
   font_size,
   font_size_adjust,
   font_stretch,
   font_style,
   font_synthesis,
   font_variant,
   font_variant_alternates,
   font_variant_caps,
   font_variant_east_asian,
   font_variant_ligatures,
   font_variant_numeric,
   font_variant_position,
   font_weight,
   grid,
   grid_area,
   grid_auto_columns,
   grid_auto_flow,
   grid_auto_rows,
   grid_column,
   grid_column_end,
   grid_column_gap,
   grid_column_start,
   grid_gap,
   grid_row,
   grid_row_end,
   grid_row_gap,
   grid_row_start,
   grid_template,
   grid_template_areas,
   grid_template_columns,
   grid_template_rows,
   hanging_punctuation,
   height,
   hyphens,
   image_rendering,
   ATimport,
   isolation,
   justify_content,
   ATkeyframes,
   left,
   letter_spacing,
   line_break,
   line_height,
   list_style,
   list_style_image,
   list_style_position,
   list_style_type,
   margin,
   margin_bottom,
   margin_left,
   margin_right,
   margin_top,
   max_height,
   max_width,
   ATmedia,
   min_height,
   min_width,
   mix_blend_mode,
   object_fit,
   object_position,
   opacity,
   order,
   orphans,
   outline,
   outline_color,
   outline_offset,
   outline_style,
   outline_width,
   overflow,
   overflow_wrap,
   overflow_x,
   overflow_y,
   padding,
   padding_bottom,
   padding_left,
   padding_right,
   padding_top,
   page_break_after,
   page_break_before,
   page_break_inside,
   perspective,
   perspective_origin,
   pointer_events,
   position,
   quotes,
   resize,
   right,
   scroll_behavior,
   tab_size,
   table_layout,
   text_align,
   text_align_last,
   text_combine_upright,
   text_decoration,
   text_decoration_color,
   text_decoration_line,
   text_decoration_style,
   text_indent,
   text_justify,
   text_orientation,
   text_overflow,
   text_shadow,
   text_transform,
   text_underline_position,
   top,
   transform,
   transform_origin,
   transform_style,
   transition,
   transition_delay,
   transition_duration,
   transition_property,
   transition_timing_function,
   unicode_bidi,
   user_select,
   vertical_align,
   visibility,
   white_space,
   widows,
   width,
   word_break,
   word_spacing,
   word_wrap,
   writing_mode,
   z_index,
}

impl PropName {
   pub fn to_str(&self) -> &str {
      match self {
         PropName::align_content => "align-content",
         PropName::align_items => "align-items",
         PropName::align_self => "align-self",
         PropName::all => "all",
         PropName::animation => "animation",
         PropName::animation_delay => "animation-delay",
         PropName::animation_direction => "animation-direction",
         PropName::animation_duration => "animation-duration",
         PropName::animation_fill_mode => "animation-fill-mode",
         PropName::animation_iteration_count => "animation-iteration-count",
         PropName::animation_name => "animation-name",
         PropName::animation_play_state => "animation-play-state",
         PropName::animation_timing_function => "animation-timing-function",
         PropName::backface_visibility => "backface-visibility",
         PropName::background => "background",
         PropName::background_attachment => "background-attachment",
         PropName::background_blend_mode => "background-blend-mode",
         PropName::background_clip => "background-clip",
         PropName::background_color => "background-color",
         PropName::background_image => "background-image",
         PropName::background_origin => "background-origin",
         PropName::background_position => "background-position",
         PropName::background_repeat => "background-repeat",
         PropName::background_size => "background-size",
         PropName::border => "border",
         PropName::border_bottom => "border-bottom",
         PropName::border_bottom_color => "border-bottom-color",
         PropName::border_bottom_left_radius => "border-bottom-left-radius",
         PropName::border_bottom_right_radius => "border-bottom-right-radius",
         PropName::border_bottom_style => "border-bottom-style",
         PropName::border_bottom_width => "border-bottom-width",
         PropName::border_collapse => "border-collapse",
         PropName::border_color => "border-color",
         PropName::border_image => "border-image",
         PropName::border_image_outset => "border-image-outset",
         PropName::border_image_repeat => "border-image-repeat",
         PropName::border_image_slice => "border-image-slice",
         PropName::border_image_source => "border-image-source",
         PropName::border_image_width => "border-image-width",
         PropName::border_left => "border-left",
         PropName::border_left_color => "border-left-color",
         PropName::border_left_style => "border-left-style",
         PropName::border_left_width => "border-left-width",
         PropName::border_radius => "border-radius",
         PropName::border_right => "border-right",
         PropName::border_right_color => "border-right-color",
         PropName::border_right_style => "border-right-style",
         PropName::border_right_width => "border-right-width",
         PropName::border_spacing => "border-spacing",
         PropName::border_style => "border-style",
         PropName::border_top => "border-top",
         PropName::border_top_color => "border-top-color",
         PropName::border_top_left_radius => "border-top-left-radius",
         PropName::border_top_right_radius => "border-top-right-radius",
         PropName::border_top_style => "border-top-style",
         PropName::border_top_width => "border-top-width",
         PropName::border_width => "border-width",
         PropName::bottom => "bottom",
         PropName::box_decoration_break => "box-decoration-break",
         PropName::box_shadow => "box-shadow",
         PropName::box_sizing => "box-sizing",
         PropName::break_after => "break-after",
         PropName::break_before => "break-before",
         PropName::break_inside => "break-inside",
         PropName::caption_side => "caption-side",
         PropName::caret_color => "caret-color",
         PropName::ATcharset => "@charset",
         PropName::clear => "clear",
         PropName::clip => "clip",
         PropName::color => "color",
         PropName::column_count => "column-count",
         PropName::column_fill => "column-fill",
         PropName::column_gap => "column-gap",
         PropName::column_rule => "column-rule",
         PropName::column_rule_color => "column-rule-color",
         PropName::column_rule_style => "column-rule-style",
         PropName::column_rule_width => "column-rule-width",
         PropName::column_span => "column-span",
         PropName::column_width => "column-width",
         PropName::columns => "columns",
         PropName::content => "content",
         PropName::counter_increment => "counter-increment",
         PropName::counter_reset => "counter-reset",
         PropName::cursor => "cursor",
         PropName::direction => "direction",
         PropName::display => "display",
         PropName::empty_cells => "empty-cells",
         PropName::filter => "filter",
         PropName::flex => "flex",
         PropName::flex_basis => "flex-basis",
         PropName::flex_direction => "flex-direction",
         PropName::flex_flow => "flex-flow",
         PropName::flex_grow => "flex-grow",
         PropName::flex_shrink => "flex-shrink",
         PropName::flex_wrap => "flex-wrap",
         PropName::float => "float",
         PropName::font => "font",
         PropName::ATfont_face => "@font-face",
         PropName::font_family => "font-family",
         PropName::font_feature_settings => "font-feature-settings",
         PropName::ATfont_feature_values => "@font-feature-values",
         PropName::font_kerning => "font-kerning",
         PropName::font_language_override => "font-language-override",
         PropName::font_size => "font-size",
         PropName::font_size_adjust => "font-size-adjust",
         PropName::font_stretch => "font-stretch",
         PropName::font_style => "font-style",
         PropName::font_synthesis => "font-synthesis",
         PropName::font_variant => "font-variant",
         PropName::font_variant_alternates => "font-variant-alternates",
         PropName::font_variant_caps => "font-variant-caps",
         PropName::font_variant_east_asian => "font-variant-east-asian",
         PropName::font_variant_ligatures => "font-variant-ligatures",
         PropName::font_variant_numeric => "font-variant-numeric",
         PropName::font_variant_position => "font-variant-position",
         PropName::font_weight => "font-weight",
         PropName::grid => "grid",
         PropName::grid_area => "grid-area",
         PropName::grid_auto_columns => "grid-auto-columns",
         PropName::grid_auto_flow => "grid-auto-flow",
         PropName::grid_auto_rows => "grid-auto-rows",
         PropName::grid_column => "grid-column",
         PropName::grid_column_end => "grid-column-end",
         PropName::grid_column_gap => "grid-column-gap",
         PropName::grid_column_start => "grid-column-start",
         PropName::grid_gap => "grid-gap",
         PropName::grid_row => "grid-row",
         PropName::grid_row_end => "grid-row-end",
         PropName::grid_row_gap => "grid-row-gap",
         PropName::grid_row_start => "grid-row-start",
         PropName::grid_template => "grid-template",
         PropName::grid_template_areas => "grid-template-areas",
         PropName::grid_template_columns => "grid-template-columns",
         PropName::grid_template_rows => "grid-template-rows",
         PropName::hanging_punctuation => "hanging-punctuation",
         PropName::height => "height",
         PropName::hyphens => "hyphens",
         PropName::image_rendering => "image-rendering",
         PropName::ATimport => "@import",
         PropName::isolation => "isolation",
         PropName::justify_content => "justify-content",
         PropName::ATkeyframes => "@keyframes",
         PropName::left => "left",
         PropName::letter_spacing => "letter-spacing",
         PropName::line_break => "line-break",
         PropName::line_height => "line-height",
         PropName::list_style => "list-style",
         PropName::list_style_image => "list-style-image",
         PropName::list_style_position => "list-style-position",
         PropName::list_style_type => "list-style-type",
         PropName::margin => "margin",
         PropName::margin_bottom => "margin-bottom",
         PropName::margin_left => "margin-left",
         PropName::margin_right => "margin-right",
         PropName::margin_top => "margin-top",
         PropName::max_height => "max-height",
         PropName::max_width => "max-width",
         PropName::ATmedia => "@media",
         PropName::min_height => "min-height",
         PropName::min_width => "min-width",
         PropName::mix_blend_mode => "mix-blend-mode",
         PropName::object_fit => "object-fit",
         PropName::object_position => "object-position",
         PropName::opacity => "opacity",
         PropName::order => "order",
         PropName::orphans => "orphans",
         PropName::outline => "outline",
         PropName::outline_color => "outline-color",
         PropName::outline_offset => "outline-offset",
         PropName::outline_style => "outline-style",
         PropName::outline_width => "outline-width",
         PropName::overflow => "overflow",
         PropName::overflow_wrap => "overflow-wrap",
         PropName::overflow_x => "overflow-x",
         PropName::overflow_y => "overflow-y",
         PropName::padding => "padding",
         PropName::padding_bottom => "padding-bottom",
         PropName::padding_left => "padding-left",
         PropName::padding_right => "padding-right",
         PropName::padding_top => "padding-top",
         PropName::page_break_after => "page-break-after",
         PropName::page_break_before => "page-break-before",
         PropName::page_break_inside => "page-break-inside",
         PropName::perspective => "perspective",
         PropName::perspective_origin => "perspective-origin",
         PropName::pointer_events => "pointer-events",
         PropName::position => "position",
         PropName::quotes => "quotes",
         PropName::resize => "resize",
         PropName::right => "right",
         PropName::scroll_behavior => "scroll-behavior",
         PropName::tab_size => "tab-size",
         PropName::table_layout => "table-layout",
         PropName::text_align => "text-align",
         PropName::text_align_last => "text-align-last",
         PropName::text_combine_upright => "text-combine-upright",
         PropName::text_decoration => "text-decoration",
         PropName::text_decoration_color => "text-decoration-color",
         PropName::text_decoration_line => "text-decoration-line",
         PropName::text_decoration_style => "text-decoration-style",
         PropName::text_indent => "text-indent",
         PropName::text_justify => "text-justify",
         PropName::text_orientation => "text-orientation",
         PropName::text_overflow => "text-overflow",
         PropName::text_shadow => "text-shadow",
         PropName::text_transform => "text-transform",
         PropName::text_underline_position => "text-underline-position",
         PropName::top => "top",
         PropName::transform => "transform",
         PropName::transform_origin => "transform-origin",
         PropName::transform_style => "transform-style",
         PropName::transition => "transition",
         PropName::transition_delay => "transition-delay",
         PropName::transition_duration => "transition-duration",
         PropName::transition_property => "transition-property",
         PropName::transition_timing_function => "transition-timing-function",
         PropName::unicode_bidi => "unicode-bidi",
         PropName::user_select => "user-select",
         PropName::vertical_align => "vertical-align",
         PropName::visibility => "visibility",
         PropName::white_space => "white-space",
         PropName::widows => "widows",
         PropName::width => "width",
         PropName::word_break => "word-break",
         PropName::word_spacing => "word-spacing",
         PropName::word_wrap => "word-wrap",
         PropName::writing_mode => "writing-mode",
         PropName::z_index => "z-index",
      }
   }
}